# Configuration Arr Monitor - Surveillance Sonarr/Radarr
applications:
  sonarr:
    enabled: true
    url: "http://localhost:8989"
    api_key: "your_sonarr_api_key"
  radarr:
    enabled: true
    url: "http://localhost:7878"
    api_key: "your_radarr_api_key"

monitoring:
  check_interval: 300           # Intervalle en secondes (5 minutes)
  max_retries: 3
  
actions:
  auto_retry: true              # Bloquer automatiquement les releases qBittorrent défaillantes et chercher de nouvelles releases
  retry_delay: 60               # Délai entre les actions (1min)
  max_retries: 3                # Nombre max de tentatives
  notify_failures: true        # Notifier les échecs persistants

logging:
  level: "INFO"                 # DEBUG|INFO|WARNING|ERROR
  file: "logs/arr-monitor.log"
  max_size_mb: 10
  backup_count: 5
